Add files via upload
d-vasily/hse_deep_learning pull request #2
Opened 2022-07-02 16:27 UTC by d-vasily

2022-07-06 20:51 UTC, AndrosovDima requested changes
Логика вычисления градиентов верна
Но дело в том, что параметры модели не должны быть завязаны на batch_size
Смещение не является матрицей, это вектор, который одинаков для каждого наблюдения батча
Исправьте это, пока что могу поставить за задание только половину баллов
Если что-то непонятно в моем пояснении - пишите ответные комментарии или мне в личку в телеграм

2022-07-09 06:21 UTC, d-vasily commented
Вопрос. 
Я поменял b на вектор, но теперь не понимаю как градиент вычислять, потому что там получается матрица, а b это вектор.
`
b1_0 = torch.randn(1, hidden_size, device=device, dtype=dtype, requires_grad=True)
b2_0 = torch.randn(1, output_size, device=device, dtype=dtype, requires_grad=True)

    h_1 = x.mm(w1) + b1
    h_relu = h_1.clamp(min=0)
    out = h_relu.mm(w2) + b2
    
    # Compute and print loss
    loss = (out - y).pow(2).sum().item()
    
    # Backward pass: 
    dloss_dout = 2 * (out - y)
    
    grad_h_1 = dloss_dout.mm(w2.t())
    grad_h_1[h_1 < 0] = 0
    
    grad_w2 = h_relu.t().mm(dloss_dout) 
    grad_b2 = dloss_dout
    
    grad_w1 = x.t().mm(grad_h_1)
    grad_b1 = grad_h_1
    
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2
    b1 -= learning_rate * grad_b1
    b2 -= learning_rate * grad_b2
 
`

И вылезает ошибка

RuntimeError                              Traceback (most recent call last)
C:\Users\VADERG~1\AppData\Local\Temp/ipykernel_14644/4203796482.py in <module>
     24     w1 -= learning_rate * grad_w1
     25     w2 -= learning_rate * grad_w2
---> 26     b1 -= learning_rate * grad_b1
     27     b2 -= learning_rate * grad_b2
     28     if t % 20 == 0:

RuntimeError: output with shape [1, 2] doesn't match the broadcast shape [64, 2]

2022-07-09 11:45 UTC, AndrosovDima commented
Да, все верно, в таком случае размерности не совпадают

Это происходит потому, что мы получаем градиент по каждому наблюдения батча для b1 и b2
А нам нужно получить суммарный градиент по всем наблюдениям батча

Получается, что если поменять в вашем коде строки:
`
grad_b2 = dloss_dout.sum()
grad_b1 = grad_h_1.sum()
`
то все сойдется:)

2022-07-09 13:16 UTC, AndrosovDima approved these changes
Теперь все верно, домашка принята!

2022-07-29 11:15 UTC, merged